export const campaignTemplates = [
  {
    id: 1,
    name: "Classic Card",
    thumbnail: "templates/vcard/classic.svg",
    description: "Traditional centered layout with profile image at the top",
    config: `{"head":{"title":"Untitled Page","description":""},"body":{"elements":[{"id":"element-R-LX_L","type":"Section","styles":{"margin":"0","padding":"0", "background": "#ffffff"},"content":[{"id":"element-tmLMSy","type":"Flex","styles":{"margin":"0","padding":"0"},"props":{"class":"relative"},"content":[{"id":"element-Ajenmp","type":"Image","props":{"src":"[BANNER_IMAGE]","alt":"Image","width":"100%","class":"cover-image"},"content":null},{"id":"element-tKiKcc","type":"Image","styles":{"margin":"[PROFILE_IMAGE_MARGIN]","borderRadius":"100%","border":"6px solid #FFFFFF"},"props":{"src":"[PROFILE_IMAGE]","alt":"Profile Picture","width":140,"height":140,"class":"[PROFILE_IMAGE_CLASS]"},"content":null}]},{"id":"element-CXohQH","type":"Flex","styles":{"margin":"[INFO_BOX_MARGIN]","flexDirection":"column","alignItems":"center"},"props":{},"content":[{"id":"element-VicgWC","type":"Heading","props":{"contenteditable":true},"content":"[TITLE]"},{"id":"element-uJiton","type":"Text","props":{"contenteditable":true},"content":"[TEXT]"},{"id":"element-N4iTP4","type":"Social","styles":{"margin":"0"},"props":{"variant":"icon-only","shape":"pill","links":[SOCIAL_LINKS]},"content":null},{"content":[CUSTOM_LINKS],"id":"element-ETjuQe","props":{},"styles":{"flexDirection":"column","alignItems":"center","padding":"0 1rem 0 1rem"},"type":"Flex"}]}]}]},"theme":{}}`,
  },
  {
    id: 2,
    name: "Minimal List",
    thumbnail: "templates/vcard/minimal.svg",
    description: "Clean, link-focused design for maximum simplicity",
    config: `{"head":{"title":"Professional Profile","description":""},"body":{"elements":[{"id":"element-A1B2C3","type":"Section","content":[{"id":"element-CXohQH","type":"Flex","styles":{"flexDirection":"column","alignItems":"center"},"props":{},"content":[{"id":"element-tKiKcc","type":"Image","styles":{"margin":"0","borderRadius":"100%","border":"6px solid #FFFFFF"},"props":{"src":"[PROFILE_IMAGE]","alt":"Image","width":200,"height":200},"content":null},{"id":"element-VicgWC","type":"Heading","styles":{"color":"#ffffff"},"props":{"contenteditable":true},"content":"[TITLE]"},{"id":"element-uJiton","type":"Text","styles":{"color":"#ffffff"},"props":{"contenteditable":true},"content":"[TEXT]"},{"id":"element-N4iTP4","type":"Social","styles":{"margin":"0"},"props":{"variant":"icon-only","shape":"pill","links":[SOCIAL_LINKS]},"content":null},{"content":[{"id":"element-3BtRYx","type":"Button","styles":{"margin":"1rem 0 0 0","borderRadius":"100px","background":"#ffffff","fontWeight":"700","color":"#333333","padding":"1.4rem"},"props":{"contenteditable":true,"variant":"default","class":"w-full max-w-md"},"content":"[PRIMARY_BUTTON]"},{"id":"element-MB6aew","type":"Button","styles":{"margin":"0","borderRadius":"100px","background":"#ffffff","padding":"1.4rem","fontWeight":"700","color":"#333333"},"props":{"contenteditable":true,"variant":"default","class":"w-full max-w-md"},"content":"[SECONDARY_BUTTON]"}],"id":"element-ETjuQe","props":{},"styles":{"flexDirection":"column","alignItems":"center","padding":"0 1rem 0 1rem"},"type":"Flex"}]}],"props":{"class":"h-screen"}, "styles": {"background": "linear-gradient(0deg, [PRIMARY_COLOR], [SECONDARY_COLOR])"}}]},"theme":{}}`,
  },
];
